export enum ConsultationsStatus {
  PENDING = 'PENDING',
  ATTENDED = 'ATTENDED',
  CANCELLED_PATIENT = 'CANCELLED_PATIENT',
  CANCELLED_DOCTOR = 'CANCELLED_DOCTOR',
  CANCELLED_ADMIN = 'CANCELLED_ADMIN',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
}
